Script started on 2020-10-21 00:48:21-06:00
]0;desmond.lau@csa1:~/cpsc355/ProjectCdesmond.lau@csa1:~/cpsc355/ProjectC$ gcc bomberman.c -o bomberman
]0;desmond.lau@csa1:~/cpsc355/ProjectCdesmond.lau@csa1:~/cpsc355/ProjectC$ ./bomberman desmond 10 10
LAUNCHING BOMBERMAN...
Welcome, desmond! Initializing your game board of size 10x10...
8.09        $       -14.49      !       3.37      8.59      10.16     13.59     6.91      8.36      
-0.77     3.36      4.73      9.41      -7.43     6.66      -6.34     7.11      14.24     -11.97    
-2.01     9.90      -7.18       *       -14.09    12.98     14.63     10.95     2.86      5.20      
1.92      -13.10      $       12.85     -5.81     -10.85    14.70     -8.33       ?       0.52      
14.66     -1.94     7.20      -10.76    -12.36    -12.64    -5.06     -6.41       ?         !       
-1.02     7.42      -13.75    -12.81    -3.53     -6.65     10.50     3.66      -3.95     14.01     
-14.01    13.33     13.93     11.22     6.56      -6.94     4.31      -5.70     9.56      14.69     
10.92     -2.14     -12.65    -3.86     -1.65     -1.31     14.25     12.33     -3.04     -3.51     
9.96      2.19        $       7.88      -4.37     2.02        ?       -8.36       $       -6.01     
2.58        ?       5.46      12.72     8.56      2.88      -3.59     -6.20       !       8.38      
Total amount of negative numbers: 39/100 (39.00% of the board, <= 40%)
Ready to go! Press 'p' to play, Press 'l' to display leaderboard and 'q' to quit.
p
You can exit the game at any time by typing in coordinate (-1,-1).
X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
Lives: 3
Score: 0.00
Bombs: 5
Enter bomb coordinates (x, y):
0 0

Bomb range increased by 2x for the next bomb

Total uncovered score: 10.67
+ $ X X X X X X X X 
- + X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
Lives: 3
Score: 10.67
Bombs: 4
Enter bomb coordinates (x, y):
4 4

YOU DIED!

YOU WON!
+ $ X X X X X X X X 
- + X X X X X X X X 
X X - * - + + X X X 
X X $ + - - + X X X 
X X + - - - - X X X 
X X - - - - + X X X 
X X + + + - + X X X 
X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
Post Game Stats: 
Lives Remaining: 2
Final Score: -2.89
Bombs Remaining: 3
Thanks for playing desmond! Press 'l' to display top scores or 'q' to quit.
l
How many top scores do you want to view?
5
------------------------------LEADERBOARD--------------------------------
 POS	NAME      			SCORE			TIME(s)
 #1	dave      			63.24			52.0
 #2	joe       			-2.22			4.0
 #3	desmond   			-2.89			9.0
 #4	desmond   			-9.69			27.0
-------------------------------------------------------------------------
]0;desmond.lau@csa1:~/cpsc355/ProjectCdesmond.lau@csa1:~/cpsc355/ProjectC$ ./bomberman desmond 10 10gcc bomberman.c -o bomberman[3P./bomberman desmond 10 10[K[K[K[K[K[K[K[K[K[K[K[K[Kabdelghani 23 23[K[K[K[K[K17 17
LAUNCHING BOMBERMAN...
Welcome, abdelghani! Initializing your game board of size 17x17...
-14.72      !       -4.02     13.49     4.41        $       12.40       *       -10.00    -4.78     -0.11     7.45      -1.22     -5.18     -5.51     -3.55     8.18      
12.39     12.96     -2.26     -6.35     -4.76     -4.07     5.22      10.66       ?       10.77       !       -6.58     -13.49    3.89      -12.46    -1.68     -14.16    
-0.96     0.48      8.57      9.90      -3.94     4.18      -13.04    -4.15     -10.61    -0.89     1.52        $         $       -3.38     -12.84      !       -12.00    
3.01        !       -6.23     11.44     -1.02     0.10      9.54        ?       13.69     0.65      -9.77     -2.43     -1.79     -12.53    5.68      -0.24     -6.70     
-11.81    -9.48     7.75      0.52      10.70       ?       8.84        ?       2.71      2.28      -14.26    6.62      12.55     -14.24    6.73        !       -13.43    
2.72        !         !       2.49        !         !       -3.52     -13.29    -4.24     0.07        ?       12.54       ?         $         $       -4.18       ?       
7.41      14.71       ?       -2.44     8.21      3.27      -7.47     -6.33     14.49     8.35      4.27      4.40      5.95      12.83     -5.31       !       5.53      
3.47      -7.76     7.67      -10.15    12.08     -14.79    12.18     2.59      4.13      6.06        !       -12.26    -0.05       $         !         $       2.05      
  $       5.52        ?       -7.46     8.09      1.11      8.46      8.27      11.69     -7.43     -2.18       $       12.90     1.86      -5.85       ?       2.95      
14.19     -8.05     8.78      9.10        $       10.21     -11.57    -0.32     -7.80     9.65      13.35     -6.98     -3.90     9.20        ?       -12.50    11.84     
7.19      -11.99    -5.39     -2.85       ?       9.90      -12.41      !       -5.21       ?       -13.83    10.08       $       13.99     -10.18      ?       7.68      
  $       4.36      -10.71    -14.61    7.45      9.61        $       14.69       $       -6.98     -13.95      $       3.69      -1.02       $       -0.67     11.73     
-7.52     -0.46     1.80      -13.24    -12.27    3.87      14.44     6.56        ?       -13.55    7.76      -12.18    11.48     1.11        !       -0.95     -8.51     
-14.36    5.35      -5.14     2.58      9.28        !         ?         !         $       -14.31    14.39     9.24      13.46     3.34      6.80      10.53       $       
4.05        ?       13.02     -14.53    -10.17    -5.56     -8.56       ?       1.24      12.48     -0.06     11.96     -12.23    -10.25    9.44      4.43      12.06     
  !       -10.42      ?       9.95      5.17      0.21      -5.62       ?       6.86      -5.28     -0.78     6.55      1.28      -2.95     3.64      -14.61      !       
-8.08     8.49      -4.25     9.23      -0.51     4.04      -9.48     -12.98    2.11      -10.98    14.11     7.44      -6.63     -11.94      $       -2.77     10.30     
Total amount of negative numbers: 110/289 (38.06% of the board, <= 40%)
Ready to go! Press 'p' to play, Press 'l' to display leaderboard and 'q' to quit.
l
How many top scores do you want to view?
5
------------------------------LEADERBOARD--------------------------------
 POS	NAME      			SCORE			TIME(s)
 #1	dave      			63.24			52.0
 #2	joe       			-2.22			4.0
 #3	desmond   			-2.89			9.0
 #4	desmond   			-9.69			27.0
-------------------------------------------------------------------------
You can exit the game at any time by typing in coordinate (-1,-1).
X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X 
Lives: 3
Score: 0.00
Bombs: 8
Enter bomb coordinates (x, y):
0 0

Total uncovered score: 10.63
- ! X X X X X X X X X X X X X X X 
+ + X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X 
Lives: 3
Score: 10.63
Bombs: 8
Enter bomb coordinates (x, y):
12 14

Bomb range increased by 2x for the next bomb

Total uncovered score: 19.13
- ! X X X X X X X X X X X X X X X 
+ + X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X - $ - X 
X X X X X X X X X X X X X + ! - X 
X X X X X X X X X X X X X + + + X 
X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X 
Lives: 3
Score: 29.76
Bombs: 8
Enter bomb coordinates (x, y):
14 3

Extra live(s) recovered!

Total uncovered score: -3.54
- ! X X X X X X X X X X X X X X X 
+ + X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X - $ - X 
X - + - - + X X X X X X X + ! - X 
X + - + + ! X X X X X X X + + + X 
X ? + - - - X X X X X X X X X X X 
X - ? + + + X X X X X X X X X X X 
X + - + - + X X X X X X X X X X X 
Lives: 5
Score: 26.23
Bombs: 8
Enter bomb coordinates (x, y):
7 12

Bomb range increased by 4x for the next bomb

Total uncovered score: 25.64
- ! X X X X X X X X X X X X X X X 
+ + X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X + + + X X X 
X X X X X X X X X X X - - $ X X X 
X X X X X X X X X X X $ + + X X X 
X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X - $ - X 
X - + - - + X X X X X X X + ! - X 
X + - + + ! X X X X X X X + + + X 
X ? + - - - X X X X X X X X X X X 
X - ? + + + X X X X X X X X X X X 
X + - + - + X X X X X X X X X X X 
Lives: 5
Score: 51.86
Bombs: 7
Enter bomb coordinates (x, y):
0 16

YOU DIED!

Bomb range increased by 2x for the next bomb

Extra bomb(s) found!

Total uncovered score: -97.39
- ! X X X X X X X X X X - - - - + 
+ + X X X X X X X X X X - + - - - 
X X X X X X X X X X X X $ - - ! - 
X X X X X X X X X X X X - - + - - 
X X X X X X X X X X X X + - + ! - 
X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X + + + X X X 
X X X X X X X X X X X - - $ X X X 
X X X X X X X X X X X $ + + X X X 
X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X - $ - X 
X - + - - + X X X X X X X + ! - X 
X + - + + ! X X X X X X X + + + X 
X ? + - - - X X X X X X X X X X X 
X - ? + + + X X X X X X X X X X X 
X + - + - + X X X X X X X X X X X 
Lives: 4
Score: 0.00
Bombs: 8
Enter bomb coordinates (x, y):
3 5

Extra bomb(s) found!

Extra live(s) recovered!

Total uncovered score: 19.44
- ! X X X X X X X X X X - - - - + 
+ + X - - - + + X X X X - + - - - 
X X X + - + - - X X X X $ - - ! - 
X X X + - + + ? X X X X - - + - - 
X X X + + ? + ? X X X X + - + ! - 
X X X + ! ! - - X X X X X X X X X 
X X X X X X X X X X X + + + X X X 
X X X X X X X X X X X - - $ X X X 
X X X X X X X X X X X $ + + X X X 
X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X - $ - X 
X - + - - + X X X X X X X + ! - X 
X + - + + ! X X X X X X X + + + X 
X ? + - - - X X X X X X X X X X X 
X - ? + + + X X X X X X X X X X X 
X + - + - + X X X X X X X X X X X 
Lives: 7
Score: 19.44
Bombs: 9
Enter bomb coordinates (x, y):
10 10

Bomb range increased by 2x for the next bomb

Extra live(s) recovered!

Total uncovered score: -8.67
- ! X X X X X X X X X X - - - - + 
+ + X - - - + + X X X X - + - - - 
X X X + - + - - X X X X $ - - ! - 
X X X + - + + ? X X X X - - + - - 
X X X + + ? + ? X X X X + - + ! - 
X X X + ! ! - - X X X X X X X X X 
X X X X X X X X X X X + + + X X X 
X X X X X X X X X X X - - $ X X X 
X X X X X X X X X X X $ + + X X X 
X X X X X X X X X + + - X X X X X 
X X X X X X X X X ? - + X X X X X 
X X X X X X X X X - - $ X - $ - X 
X - + - - + X X X X X X X + ! - X 
X + - + + ! X X X X X X X + + + X 
X ? + - - - X X X X X X X X X X X 
X - ? + + + X X X X X X X X X X X 
X + - + - + X X X X X X X X X X X 
Lives: 8
Score: 10.77
Bombs: 8
Enter bomb coordinates (x, y):
0 5

YOU WON!
- ! X + + $ + * X X X X - - - - + 
+ + X - - - + + X X X X - + - - - 
X X X + - + - - X X X X $ - - ! - 
X X X + - + + ? X X X X - - + - - 
X X X + + ? + ? X X X X + - + ! - 
X X X + ! ! - - X X X X X X X X X 
X X X X X X X X X X X + + + X X X 
X X X X X X X X X X X - - $ X X X 
X X X X X X X X X X X $ + + X X X 
X X X X X X X X X + + - X X X X X 
X X X X X X X X X ? - + X X X X X 
X X X X X X X X X - - $ X - $ - X 
X - + - - + X X X X X X X + ! - X 
X + - + + ! X X X X X X X + + + X 
X ? + - - - X X X X X X X X X X X 
X - ? + + + X X X X X X X X X X X 
X + - + - + X X X X X X X X X X X 
Post Game Stats: 
Lives Remaining: 8
Final Score: 41.07
Bombs Remaining: 7
Thanks for playing abdelghani! Press 'l' to display top scores or 'q' to quit.
l
How many top scores do you want to view?
6
------------------------------LEADERBOARD--------------------------------
 POS	NAME      			SCORE			TIME(s)
 #1	dave      			63.24			52.0
 #2	abdelghani			41.07			72.0
 #3	joe       			-2.22			4.0
 #4	desmond   			-2.89			9.0
 #5	desmond   			-9.69			27.0
-------------------------------------------------------------------------
]0;desmond.lau@csa1:~/cpsc355/ProjectCdesmond.lau@csa1:~/cpsc355/ProjectC$ exit
exit

Script done on 2020-10-21 00:50:46-06:00
