Script started on 2020-12-09 15:17:01-07:00
]0;desmond.lau@csa1:~/cpsc355/projdesmond.lau@csa1:~/cpsc355/proj$ make
m4 p1.asm > p1.s
m4 p2.asm > p2.s
as p1.s -g -o p1.o
as p2.s -g -o p2.o
gcc p1.o p2.o -g -o proj
]0;desmond.lau@csa1:~/cpsc355/projdesmond.lau@csa1:~/cpsc355/proj$ ./proj
Error: Invalid board size/number of arguments. Exiting program. 
]0;desmond.lau@csa1:~/cpsc355/projdesmond.lau@csa1:~/cpsc355/proj$ ./proj desmond `0[K[K9 9
Error: Invalid board size/number of arguments. Exiting program. 
]0;desmond.lau@csa1:~/cpsc355/projdesmond.lau@csa1:~/cpsc355/proj$ ./proj desmond 9 9[K[K[K10 10
-8.91      -5.17      ^          $          *          -3.55      -5.05      -14.15     9.35       2.78       
9.00       $          1.73       -2.51      12.72      0.80       -3.35      ^          &          11.56      
5.42       -1.29      $          10.68      -10.89     -12.14     ^          3.40       3.20       6.55       
^          7.38       -4.68      -5.12      &          6.65       -10.55     -13.65     6.12       12.35      
-13.98     &          6.55       -10.88     -3.62      14.65      ^          -12.91     9.58       1.38       
-5.96      2.03       6.65       &          &          4.30       -6.35      -0.49      -13.40     -6.97      
-7.35      -12.31     -13.66     -3.31      12.06      -11.59     &          -7.13      13.94      $          
-11.13     -3.49      -4.20      -1.86      ^          -1.80      -4.56      11.18      -2.32      3.95       
^          -1.56      ^          -11.24     ^          13.47      $          -0.27      1.50       -13.32     
-11.39     9.21       2.16       14.60      9.85       3.22       10.88      2.34       3.63       2.78       
negative numbers 41/100 = 41.00% 
positive numbers 38/100 = 38.00% 
special tiles 21/100 = 21.00% 
Press 1 to start the game, 2 to view leaderboard, 3 to quit.
2
How many scores do you want to view?
1
... sorting scores ...
... retrieving data ...
... error: sorting failed. 
Name: obama Score: 109.27 Time: 39s
X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
Lives: 3 
Score: 0.00 
Bombs: 4 
To quit type 999 as both coordinates.
Enter the bomb x-coordinate: 
0
Enter the bomb y-coordinate: 
0
Bomb range increased by 2x for the next bomb.
Total uncovered score: -5.09
- - X X X X X X X X 
+ $ X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
Lives: 2 
Score: 0.00 
Bombs: 3 
To quit type 999 as both coordinates.
Enter the bomb x-coordinate: 
9
Enter the bomb y-coordinate: 
9
Total uncovered score: 9.48
- - X X X X X X X X 
+ $ X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X X X X 
X X X X X X X + - + 
X X X X X X X - + - 
X X X X X X X + + + 
Lives: 2 
Score: 9.48 
Bombs: 2 
To quit type 999 as both coordinates.
Enter the bomb x-coordinate: 
4
Enter the bomb y-coordinate: 
5
You found bonus points. 
Extra lives found. 
You found bonus points. 
Total uncovered score: 105.08
- - X X X X X X X X 
+ $ X X X X X X X X 
X X X X X X X X X X 
X X X X & + - X X X 
X X X X - + ^ X X X 
X X X X & + - X X X 
X X X X X X X X X X 
X X X X X X X + - + 
X X X X X X X - + - 
X X X X X X X + + + 
Lives: 3 
Score: 114.56 
Bombs: 1 
To quit type 999 as both coordinates.
Enter the bomb x-coordinate: 
0
Enter the bomb y-coordinate: 
4
YOU WIN. 
- - X $ * - X X X X 
+ $ X - + + X X X X 
X X X X X X X X X X 
X X X X & + - X X X 
X X X X - + ^ X X X 
X X X X & + - X X X 
X X X X X X X X X X 
X X X X X X X + - + 
X X X X X X X - + - 
X X X X X X X + + + 
Lives: 3 
Score: 114.56 
Bombs: 1 
Press 1 to view leaderboard and 2 to quit.
2
]0;desmond.lau@csa1:~/cpsc355/projdesmond.lau@csa1:~/cpsc355/proj$ ./proj desmond 10 10[K[K[K[K5 15
12.04      14.71      7.66       -11.23     14.80      -4.74      &          ^          8.50       -2.11      2.09       -14.14     12.85      ^          -7.07      
4.13       1.93       -11.62     8.68       ^          0.33       9.96       -0.72      *          -14.05     -8.56      7.13       -5.83      -4.67      12.75      
-13.33     -13.66     -6.62      -6.34      -9.87      -14.13     -10.46     11.92      13.32      -11.33     1.02       4.75       6.63       -9.76      13.27      
-13.01     13.49      -11.44     5.42       12.68      $          ^          &          7.99       -4.21      8.86       -4.43      5.96       -3.02      -7.73      
-4.92      -0.26      &          $          ^          -6.99      10.36      9.25       ^          1.14       -6.11      &          ^          9.00       -11.67     
-11.02     4.68       -4.32      9.18       $          -0.93      $          -6.64      4.21       $          2.31       $          $          -2.90      6.58       
-11.90     -4.08      $          1.84       -4.37      14.84      -2.04      14.25      $          -5.77      &          ^          $          10.98      ^          
-9.02      -1.15      $          8.57       ^          -9.20      11.24      -9.49      14.62      $          -2.54      -12.52     1.76       6.91       -13.90     
8.26       -1.46      12.70      -5.19      -4.81      ^          0.06       12.58      13.34      4.26       1.16       ^          6.20       4.63       &          
-13.70     10.70      10.77      6.35       ^          -0.57      &          -1.59      -10.67     6.94       0.55       -13.25     -13.28     5.36       -5.18      
5.49       5.05       $          ^          0.90       -4.42      3.82       10.79      14.55      $          -5.09      -9.90      -4.06      3.91       -10.71     
-11.61     $          11.87      -0.41      10.11      5.15       10.24      -3.14      ^          &          -4.38      -10.29     ^          1.44       -0.47      
-2.31      -14.95     8.13       -7.20      13.53      6.23       -11.61     $          -14.28     -2.19      -7.11      13.69      12.15      -14.00     $          
12.30      &          -9.94      2.39       -0.66      -0.38      -12.28     -9.97      6.12       -3.11      14.21      &          -7.67      -5.82      -8.87      
11.85      0.01       13.29      6.26       12.38      -13.46     5.17       -7.81      $          13.73      -7.40      -1.54      &          9.77       10.24      
negative numbers 90/225 = 40.00% 
positive numbers 89/225 = 39.56% 
special tiles 46/225 = 20.44% 
Press 1 to start the game, 2 to view leaderboard, 3 to quit.
3
]0;desmond.lau@csa1:~/cpsc355/projdesmond.lau@csa1:~/cpsc355/proj$ ./proj desmond 15 15
11.56      -1.32      -12.69     &          10.76      6.07       *          &          -4.02      -14.10     5.19       1.74       2.06       -14.75     ^          
2.24       $          ^          -14.62     -6.76      5.80       ^          5.21       ^          8.72       9.39       4.30       6.98       ^          &          
&          -1.57      2.08       -4.18      12.29      -1.51      12.90      -8.05      ^          -0.61      -6.59      13.25      -12.16     ^          -7.65      
3.94       -4.45      -1.35      -9.40      0.65       3.85       3.28       8.19       -1.09      $          &          &          6.76       0.04       9.44       
9.09       12.94      &          7.68       ^          -4.65      -6.74      14.16      &          -0.15      -10.39     -10.11     -8.49      4.73       ^          
2.00       &          6.87       12.38      9.20       -1.26      -8.01      6.89       14.38      2.11       -7.27      13.14      9.52       &          -9.05      
-12.98     ^          5.93       4.46       -1.42      -8.69      ^          7.19       11.59      -3.73      $          7.33       4.97       -13.39     12.69      
10.37      -11.17     ^          6.34       -14.21     2.27       -12.27     7.93       -13.50     &          ^          -8.66      14.74      10.63      -0.98      
-14.19     -1.46      -0.81      7.49       -2.14      -10.17     5.30       -0.37      1.35       -5.07      -8.71      7.62       14.46      -2.79      -14.63     
-4.37      4.73       $          -1.62      -11.71     -13.14     -7.03      5.77       11.07      1.71       -6.83      -1.63      8.94       1.17       $          
-8.75      &          12.12      2.89       $          3.11       1.13       3.57       -9.07      4.68       $          -12.77     &          2.56       -0.75      
14.67      5.76       -12.65     -7.85      $          ^          &          -11.54     -6.14      -2.91      14.16      3.91       -14.78     14.88      &          
-6.34      -14.18     7.06       2.60       -8.74      -10.65     -9.81      12.72      -10.51     -8.39      9.49       13.93      -8.28      -3.61      -4.60      
10.16      13.16      -11.54     -13.38     -13.03     10.08      -2.36      -5.97      ^          ^          8.42       7.99       -12.37     -13.78     0.16       
-13.19     12.21      &          10.68      -0.89      9.03       1.44       ^          &          9.07       11.91      -8.02      9.78       7.69       -7.40      
negative numbers 88/225 = 39.11% 
positive numbers 94/225 = 41.78% 
special tiles 43/225 = 19.11% 
Press 1 to start the game, 2 to view leaderboard, 3 to quit.
1
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
Lives: 3 
Score: 0.00 
Bombs: 5 
To quit type 999 as both coordinates.
Enter the bomb x-coordinate: 
0
Enter the bomb y-coordinate: 
14
Extra lives found. 
Extra lives found. 
You found bonus points. 
Total uncovered score: 35.25
X X X X X X X X X X X X X - ^ 
X X X X X X X X X X X X X ^ & 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
Lives: 5 
Score: 35.25 
Bombs: 4 
To quit type 999 as both coordinates.
Enter the bomb x-coordinate: 
10
Enter the bomb y-coordinate: 
10
Bomb range increased by 2x for the next bomb.
Total uncovered score: 0.31
X X X X X X X X X X X X X - ^ 
X X X X X X X X X X X X X ^ & 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X + - - X X X 
X X X X X X X X X + $ - X X X 
X X X X X X X X X - + + X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
Lives: 5 
Score: 35.56 
Bombs: 3 
To quit type 999 as both coordinates.
Enter the bomb x-coordinate: 
0
Enter the bomb y-coordinate: 
12
Extra lives found. 
Total uncovered score: 16.51
X X X X X X X X X X + + + - ^ 
X X X X X X X X X X + + + ^ & 
X X X X X X X X X X - + - ^ - 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X + - - X X X 
X X X X X X X X X + $ - X X X 
X X X X X X X X X - + + X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
Lives: 6 
Score: 52.07 
Bombs: 2 
To quit type 999 as both coordinates.
Enter the bomb x-coordinate: 
4
Enter the bomb y-coordinate: 
5
Extra lives found. 
Total uncovered score: -3.67
X X X X X X X X X X + + + - ^ 
X X X X X X X X X X + + + ^ & 
X X X X X X X X X X - + - ^ - 
X X X X + + + X X X X X X X X 
X X X X ^ - - X X X X X X X X 
X X X X + - - X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X + - - X X X 
X X X X X X X X X + $ - X X X 
X X X X X X X X X - + + X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
X X X X X X X X X X X X X X X 
Lives: 7 
Score: 48.39 
Bombs: 1 
To quit type 999 as both coordinates.
Enter the bomb x-coordinate: 
0 14
Enter the bomb y-coordinate: 
0
Total uncovered score: 22.34
GAME OVER. 
Press 1 to view leaderboard and 2 to quit.
1
How many top scores do you want to view?
1
... sorting scores ...
... retrieving data ...
... error: sorting failed. 
Name: obama Score: 109.27 Time: 39s
]0;desmond.lau@csa1:~/cpsc355/projdesmond.lau@csa1:~/cpsc355/proj$ exit
exit

Script done on 2020-12-09 15:20:15-07:00
